name: Deploy RCP Manual

on:
  workflow_dispatch:
    inputs:
      upload_docker:
        type: boolean
        description: Upload artifact to docker
      deploy_test:
        type: boolean
        description: Deploy to TEST
      commit_id:
        decription: commit id (optional)
      build_params:
        type: choice
        description: build parameters
        default: ''
        options:
          - ''
          - -DskipTests
          - -DskipITs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_id }}

      - name: Job parameters
        run: |
          if [ ${{ github.event.inputs.deploy_test=='true' }} ]; then
            echo "deploy_test is true, setting upload_docker to true..."
          fi

          echo "upload_docker: ${{ github.event.inputs.upload_docker }}"
          echo "deploy_test: ${{ github.event.inputs.deploy_test }}"
          echo "commit_id: ${{ github.event.inputs.commit_id }}"
          echo "build_params: ${{ github.event.inputs.build_params }}"

      - name: Print README Content
        run: |
          cat test.md # Assumes the README file is named README.md
        shell: bash

      - name: build project
        run: |
          echo "BUILD SUCCESS"

      - name: login to kumo-docker-release-local
        if: ${{ github.event.inputs.upload_docker=='true' }}
        run: |
          echo "logged in to docker"

      - name: Build and Push Docker image
        if: ${{ github.event.inputs.upload_docker=='true' }}
        run: |
          echo "pushed image to docker"

  pipeline:
    if: ${{  github.event.inputs.upload_docker=='true' && github.event.inputs.deploy_test=='true' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: trigger spinnaker pipeline
        run: echo 'pipeline triggered after pushing artifact to docker, deploy_test= ${{  github.event.inputs.upload_docker && github.event.inputs.deploy_test }}'